# To trigger a Travis-CI build for every GitHub push or Pull Request:
# 1. Goto https://travis-ci.org/profile/KFDing
# 2. Flip the switch for the `pm4knime-maven` repo
language: java
matrix:
 fast_finish: true
 include:
 - os: linux
   jdk: openjdk8
   script: xvfb-run mvn verify -B
 - os: osx
   osx_image: xcode8.3
   before_install: export JAVA_HOME=$(/usr/libexec/java_home)
   script: Xvfb :5009 & export DISPLAY=:5009 && mvn verify -B
cache:
  directories:
   - $HOME/.m2
   - $HOME/.sonar/cache
install: mvn package -B
## Uncomment below to perform SonarCloud (https://sonarcloud.io/) analysis,
## Next steps to have automated SonarCloud analysis reports for the repository:
## 1. Create organization at https://sonarcloud.io/account/organizations with 'KFDing' as name and 'kfding' as key
## 2. Add SONAR_TOKEN env var to Travis-CI settings, a token can be generated at https://sonarcloud.io/account/security/
## 3. Push a change to GitHub to trigger a Travis-CI build and SonarCloud analysis
#after_success:
#- mvn sonar:sonar -Dsonar.login=$SONAR_TOKEN
